<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config['page_query_string'] = TRUE;
$config['query_string_segment'] = 'page';
$config['num_links'] = 3;
$config['full_tag_open'] = '<ul class="pagination">';
$config['full_tag_close'] = '</ul>';
$config['num_tag_open'] = '<li class="page-item">';
$config['num_tag_close'] = '</li>';
$config['cur_tag_open'] = '<li class="page-item active"><a class="page-link" href="#">';
$config['cur_tag_close'] = '</a></li>';
$config['last_tag_open'] = '<li>';
$config['last_tag_close'] = '</li>';
$config['first_tag_open'] = '<li>';
$config['first_tag_close'] = '</li>';
$config['prev_tag_open'] = '<li>';
$config['prev_tag_close'] = '</li>';
$config['last_tag_open'] = '<li class="hide">';
$config['last_tag_close'] = '</li>';
$config['use_page_numbers'] = TRUE;
$config['next_tag_open'] = '<li class="page-item">';
$config['next_tag_close'] = '</li>';
$config['first_link'] = '首页';
$config['prev_link'] = '上一页';
$config['next_link'] = '下一页';
$config['last_link'] = '末页';
$config['class'] = 'page-link';

